name: CI

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: Swift version
        run: swift --version

      - name: Resolve dependencies
        run: swift package resolve

      - name: Build
        run: swift build -v

      - name: Test
        run: swift test -v
